#!/usr/bin/bash

source ~/.cache/wal/colors.sh

while getopts li flag
do
	case "${flag}" in
	i)
		grim ~/.cache/lockscreen/background 
		#gm convert ~/.cache/lockscreen/background -blur 9x5 ~/.cache/lockscreen/background
		#gm convert ~/.cache/lockscreen/background  -fill black -colorize 20% ~/.cache/lockscreen/background
		;;
	l)
		swaylock --ring-color ${color15} \
			--key-hl-color ${color14} \
			--bs-hl-color ${color9} \
			--caps-lock-key-hl-color ${color13} \
			--caps-lock-bs-hl-color {$color10} \
			--inside-caps-lock-color ${color0} \
			--text-caps-lock-color ${color15} \
			--inside-ver-color ${color0} \
			--text-ver-color ${color14} \
			--ring-ver-color ${color14} \
			--inside-wrong-color ${color0} \
			--text-wrong-color ${color9} \
			--ring-wrong-color ${color9} \
			--inside-clear-color ${color0} \
			--ring-clear-color ${color13} \
			--text-clear-color ${color13} \
			--font ProFontIIxNerdFont \
			--indicator-radius 100 \
			--indicator-thickness 15 \
			-i ~/.cache/lockscreen/background
					;;
	esac
done

