#!/usr/bin/bash
selection=~/Pictures/Wallpapers/$(ls ~/Pictures/Wallpapers | wofi --dmenu)

if [ $? -eq 0 ]; then
	opacity=$(printf "0\n10\n20\n30\n40\n50\n60\n70\n80\n90\n99" | wofi --dmenu --exec-search)
	if [ $? -eq 0 ]; then
		contrast=$(printf "0\n0.1\n0.2\n0.3\n0.4\n0.5\n0.6\n0.7\n0.8\n0.9\n1" | wofi --dmenu --exec-search)
		~/.local/share/scripts/swaywall $selection $opacity $contrast
	fi
fi
echo $selection
echo $opacity
echo $contrast
