#!/usr/bin/env python3

import subprocess
import os
with open('/home/aditya/.local/state/playbackctl/playercurrent', 'r') as file:
    current = file.read()

proc = subprocess.Popen(["playerctl", "-l"], stdout=subprocess.PIPE)
out = proc.communicate()[0].decode('ascii')
outlist = out.split('\n')[:-1]

for i in range(len(outlist)):
    player = outlist[i]
    if current == player:
        nextplayer = outlist[i + 1] if len(outlist) > (i + 1) else outlist[0]
        with open('/home/aditya/.local/state/playbackctl/playercurrent', 'w') as file:
            file.write(nextplayer)
        break
